apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
  namespace: {{ .Values.namespace }}
  labels:
    name: deployer

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-functions
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-admin
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: {{ .Values.namespace }}
- kind: ServiceAccount
  name: jenkins
  namespace: kube-system