# This allows user to gain access to view kube-system namespace.
# Required until we start using helm 3 and understand if there is any security risk of viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.namespace }}-users
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view 
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: {{ .Values.namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.namespace }}-helmers
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: helmer 
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: {{ .Values.namespace }}
- kind: ServiceAccount
  name: jenkins
  namespace: kube-system

---